ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_type_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_type_check CHECK (type IN (
  'RESERVATION_CREATED', 'RESERVATION_CANCELLED', 'RESERVATION_RESCHEDULED',
  'RESERVATION_DELIVERED', 'RESERVATION_NO_SHOW', 'ORDER_EXPIRED',
  'BRANCH_REQUEST_REVIEWED'
));
